# Generated by Django 5.0.3 on 2024-04-20 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_data_rename_loast_name_student_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='phone_number',
            new_name='studentage',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='studentname',
        ),
        migrations.RemoveField(
            model_name='data',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='data',
            name='emailaddress',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
